### ISSUE TITLE
Build issue: com.gigya.native_screensets_engine cannot be found

### ISSUE THREAD

**Issue by rlemasquerier** [SAP/gigya-android-sdk#1]
Hi there !

I'm trying to rebuild the SDK locally, and I noticed that`com.gigya.native_screensets_engine` dependency has been kept as a local one :

https://github.com/SAP/gigya-android-sdk/blob/2f844fd121a381a8d5513dcab4fff1a9c4988af9/build.gradle#L29

It makes it not possible to rebuild the `sdk-nss` package

**Comment by tal-mi** [comment]
Hi,
Gigya NSS integration is available via this document:
https://developers.gigya.com/display/GD/Native+Screen-Sets
This repo is due to have major changes & updates soon.

Thanks.
