### ISSUE TITLE
Social Google Android disallowed_useragent

### ISSUE THREAD

**Issue by ghena** [SAP/gigya-android-sdk#11]
Dear sirs,

working with React Native we found a problem during WebLoginActivity signin.
We fix in this way:

alter:gigya-android-sdk\sdk-core\src\main\java\com\gigya\android\sdk\ui\WebLoginActivity.java
#row 160
adding:
        **webView.getSettings().setUserAgentString(System.getProperty("http.agent"));**

Maybe can help someone else.
Regards.

**Comment by tal-mi** [comment]
Social login with Google is not permitted over WebView and SDK should specifically use the GoogleProvider (which requires Google auth SDK to be implemented).
Are you using a different flow?

**Comment by ghena** [comment]
Hi,
we implemented as suggested 
    implementation 'com.google.android.gms:play-services-auth:18.1.0'

But Gigya flow for google seems use always webLoginActivity.
We need to implement another library ?

For your information with this fix we are able to Login correctly.

**Comment by tal-mi** [comment]
If your login flow is directed to the WebLoginActivity it means the SDK cannot find the GoogleProvider and should throw a RuntimeException. (ProviderFactory.java class 86 - 92).
What SDK version are u using?

**Comment by ghena** [comment]
Before fix we are using 4.2.1.aar

But to fix we generate aar cloning sdk repository and using assembleReleaseAar command.

**Comment by tal-mi** [comment]
You should look closely at your Google setup.
Your fix (appreciate it) is a sort of a hack which we cannot use because Google strictly disallows logging in using embedded WebViews.

**Comment by ghena** [comment]
![image](https://user-images.githubusercontent.com/548424/99651566-105d3f80-2a57-11eb-8110-b6a989545d1d.png)

We did as specified in this setup native login.
We miss something more ?

**Comment by tal-mi** [comment]
Seems right if your app is properly configured to use Google services.
 Yet my tests without "implementation 'com.google.android.gms:play-services-auth:18.1.0'" will cause a Runtime Exception.

I will continue to test this issue and update if I find something.

**Comment by ghena** [comment]
I can send you my old 4.2.1.aar in you need.

**Comment by tal-mi** [comment]
Please do.

**Comment by ghena** [comment]
[gigya-android-sdk-4.2.1.zip](https://github.com/SAP/gigya-android-sdk/files/5566606/gigya-android-sdk-4.2.1.zip)

**Comment by tal-mi** [comment]
Thanks.
I will update as soon as I can.

**Comment by tal-mi** [comment]
Hi, 
Tested with version sent.
When Google is implemented correctly it will not open in the WebLoginActivity.
Please recheck your implementation.

**Comment by ghena** [comment]
Hi,
have you tested with react native or with android directly ?

Could you share your demo version ?

Thanks.

**Comment by tal-mi** [comment]
Hi,
We test and support Android directly.
The demo application is available in the repo (example-kotlin).
We currently do not support React Native officially but if needed you can open a [support ticket](https://developers.gigya.com/display/GD/Opening+A+Support+Incident)

**Comment by qduborper** [comment]
Hello @ghena, I had the same issue from my side. and just realised that I need to change

`mGigya.login("googleplus", parameters, getGigyaLoginHandler(promise));`

to 

`mGigya.login(GigyaDefinitions.Providers.GOOGLE, parameters, getGigyaLoginHandler(promise));`

if it can help. I was using "googleplus" as provider name, which is now "google" so native google auth can be used instead of webview

**Comment by tal-mi** [comment]
Hi,

React-Native plugin is currently in development and its first preview expected to release in the upcoming weeks.

Regards,
Tal
