### ISSUE TITLE
Can't retrieve core-v5.0.0 from jitpack

### ISSUE THREAD

**Issue by cristan** [SAP/gigya-android-sdk#12]
https://github.com/SAP/gigya-android-sdk/tree/master/sdk-core states I should add this line to my build.gradle:

`implementation 'com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v5.0.0'`

When I do that, I get the following error:

```
Could not determine the dependencies of task ':app:compileProdDebugKotlin'.
> Could not resolve all files for configuration ':app:mockDebugRuntimeClasspath'.
   > Could not find com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v5.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.0.0/gigya-android-sdk-core-core-v5.0.0.pom
       - https://jcenter.bintray.com/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.0.0/gigya-android-sdk-core-core-v5.0.0.pom
       - https://jitpack.io/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.0.0/gigya-android-sdk-core-core-v5.0.0.pom
       - https://plugins.gradle.org/m2/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.0.0/gigya-android-sdk-core-core-v5.0.0.pom
```

As you can see: the following URL is used:
https://jitpack.io/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.0.0/gigya-android-sdk-core-core-v5.0.0.pom

This gives a 404. There actually is something there at the following URL:
https://jitpack.io/com/github/SAP/gigya-android-sdk/core-v5.0.0/gigya-android-sdk-core-v5.0.0.pom

This means that either your documentation or your files at the jitpack repo should be changed.

**Comment by tal-mi** [comment]
Hi, 

You are correct. I will update the links shortly.

**Comment by tal-mi** [comment]
Fixed.
You should be able to use the following
implementation 'com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v5.0.0'
as stated in documentation.
