### ISSUE TITLE
Unclear exception when GSON isn't added

### ISSUE THREAD

**Issue by cristan** [SAP/gigya-android-sdk#14]
When you use Gigya without adding the GSON library, the following exception is thrown in your getInstance method:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/Gson;`

However, this is swallowed and the following is called:

`throw new RuntimeException("Error creating Gigya SDK (did you forget to Gigya.setApplication or missing apiKey?)Error creating Gigya SDK (did you forget to Gigya.setApplication or missing apiKey?)");`

First of all, this contains a copy>paste error: the same message is here twice. Second of all: this exception wasn't caused by me forgetting to call Gigya.setApplication or a missing apiKey.

So please make your project or detect this NoClassDefFoundError and use that to throw an exception with a more descriptive text. A better solution would (IMO) be to add GSON as a dependency of your project so people won't have to worry about adding GSON as a dependency. Maybe it's an idea to make the caught error the parent of the exception for cases like these where not calling Gigya.setApplication or missing apiKey isn't the actual problem. 

In either case: fix the duplicate text in your exception.

**Comment by tal-mi** [comment]
Thank you,

Will definitely look into that exception.
As for the GSON dependency, it is currently required and documented as such. We will not create a "fat" AAR that will include the GSON library.

Regards,
Tal

**Comment by tal-mi** [comment]
Hi,

Version 5.1.0 contains a specific exception for missing GSON in the host application.
