### ISSUE TITLE
Add read timeout to HttpNetworkProvider

### ISSUE THREAD

**Issue by outadoc** [SAP/gigya-android-sdk#16]
Hello,

The `VolleyNetworkProvider` sets a 30-second timeout to HTTP calls.

The `HttpNetworkProvider`, however, only sets a 10-second **connect** timeout, and no read timeout.

This means that if a client connects successfully to the Gigya servers, but fails to read the response, the app will keep loading and never time out.

It would be nice if a read timeout was specified in `HttpNetworkProvider` as well, via `URLConnection.setReadTimeout(...)`, so that we don't have to add a dependency on Volley to benefit from it.

Thank you!

**Comment by tal-mi** [comment]
Hi,

Thank you for reporting the issue. 
It will be addressed in the upcoming update cycle.

Regards,
Tal

**Comment by tal-mi** [comment]
Hi,

Version 5.1.0 connection timeout set to 30 & read timeout set to 15.
We will have these fields available for configuration in the next version.

**Comment by outadoc** [comment]
Great, thank you!
