### ISSUE TITLE
Facebook login Chrome Tab is closed when resuming activity

### ISSUE THREAD

**Issue by erickok** [SAP/gigya-android-sdk#17]
We are, among others, supporting login via Facebook. For this, we have added the Facebook login SDK (tested with version 7.1 and 9.0). For a basic login flow this works well - if you stay in the app. However, if you would back out of the app during the Facebook login flow and then come back, your login is reset. 

For example, you start a social Facebook login. If do not have the Facebook app installed, so i am presented a login screen in a Chrome Tab.

![Screenshot 2021-02-22 at 14 18 11](https://user-images.githubusercontent.com/196453/108713641-cd5cad80-7518-11eb-90fe-7ec10c2c55be.png)

I now press the multi-task button of my Android device (which pauses the app) and then return to the app again. The login flow is now reset (no longer showing the Facebook login Chrome Tab) and thrown back to my own app screen. I do get a callback into `onOperationCanceled`.

This is problematic because if you use two-factor authentication with Facebook you (typically, as an end-user) have to back out of the app to find your 2-factor auth token in some other app. If you then go back to enter this token, the login flow was reset and you can not log in.

It seems your example, which uses the old Facebook 5.0 SDK, did not have this issue, so you might not be aware. However, it is blocking our users who use 2-factor authentication with Facebook and do not have the Facebook app installed.

**Comment by tal-mi** [comment]
Hi,

The cancel event originates from the Facebook SDK.

**Comment by tal-mi** [comment]
Hi,

This is confirmed as a Facebook SDK bug. 
I am monitoring it and awaiting resolution. A workaround is currently not available.

**Comment by tal-mi** [comment]
Hi,

Facebook has confirmed that they will fix this issue in their next release of the Android SDK.
I will update this thread after confirmation.

Regards,
Tal
