### ISSUE TITLE
Login result fails to save on Huawei P30 Lite, which requires the user to login anew for every cold start of the app

### ISSUE THREAD

**Issue by IuliaSTANA** [SAP/gigya-android-sdk#19]
**SDK version:**
`com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v5.1.0`
`com.android.volley:volley:1.2.0`
Although I see this behavior with `core-v5.0.1` and `volley:1.1.1` as well
**Device**: Huawei P30 Lite, Android 9.

**Repro steps:**
Login successfully with email and password. Credentials are available in memory and I am logged in. 
Restart the application.
Result: I am no longer logged in and the `gigya.session` instance is null.
The Huawei P30 is the only device I see this happening on.

**Checked on:**
* Pixel2 with Android 11 
* OnePlus 8 Pro with Android 11
* Galaxy J5 with Android 7.1.1
Where it works fine.
 
While I am able to login successfully, saving the result of the login to the permanent storage fails with the following stacktrace:

`W/System.err: java.security.InvalidKeyException: Key for algorithm null not suitable for symmetric enryption.
W/System.err:     at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(BaseBlockCipher.java:519)
W/System.err:     at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(BaseBlockCipher.java:1076)
W/System.err:     at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
W/System.err:     at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
W/System.err:     at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
W/System.err:     at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
W/System.err:     at javax.crypto.Cipher.init(Cipher.java:1143)
W/System.err:     at javax.crypto.Cipher.init(Cipher.java:1084)
W/System.err:     at com.gigya.android.sdk.session.SessionService.encryptSession(SessionService.java:66)
W/System.err:     at com.gigya.android.sdk.session.SessionService.save(SessionService.java:114)
W/System.err:     at com.gigya.android.sdk.session.SessionService.setSession(SessionService.java:178)
W/System.err:     at com.gigya.android.sdk.api.BusinessApiService.updateWithNewSession(BusinessApiService.java:64)
W/System.err:     at com.gigya.android.sdk.api.BusinessApiService.handleAccountApiResponse(BusinessApiService.java:83)
W/System.err:     at com.gigya.android.sdk.api.BusinessApiService.access$000(BusinessApiService.java:32)
W/System.err:     at com.gigya.android.sdk.api.BusinessApiService$3.onApiSuccess(BusinessApiService.java:184)
W/System.err:     at com.gigya.android.sdk.api.ApiService$1.onResponse(ApiService.java:120)
W/System.err:     at com.gigya.android.sdk.network.adapter.VolleyNetworkProvider$2.onResponse(VolleyNetworkProvider.java:184)
W/System.err:     at com.gigya.android.sdk.network.adapter.VolleyNetworkProvider$2.onResponse(VolleyNetworkProvider.java:179)
W/System.err:     at com.gigya.android.sdk.network.adapter.VolleyNetworkProvider$VolleyNetworkRequest.deliverResponse(VolleyNetworkProvider.java:281)
W/System.err:     at com.gigya.android.sdk.network.adapter.VolleyNetworkProvider$VolleyNetworkRequest.deliverResponse(VolleyNetworkProvider.java:219)
W/System.err:     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:907)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:216)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
W/System.err: com.gigya.android.sdk.encryption.EncryptionException: encryptSession: exceptionKey for algorithm null not suitable for symmetric enryption.
W/System.err:     at com.gigya.android.sdk.session.SessionService.encryptSession(SessionService.java:71)
W/System.err:     at com.gigya.android.sdk.session.SessionService.save(SessionService.java:114)
W/System.err:     at com.gigya.android.sdk.session.SessionService.setSession(SessionService.java:178)
W/System.err:     at com.gigya.android.sdk.api.BusinessApiService.updateWithNewSession(BusinessApiService.java:64)
W/System.err:     at com.gigya.android.sdk.api.BusinessApiService.handleAccountApiResponse(BusinessApiService.java:83)
W/System.err:     at com.gigya.android.sdk.api.BusinessApiService.access$000(BusinessApiService.java:32)
W/System.err:     at com.gigya.android.sdk.api.BusinessApiService$3.onApiSuccess(BusinessApiService.java:184)
W/System.err:     at com.gigya.android.sdk.api.ApiService$1.onResponse(ApiService.java:120)
W/System.err:     at com.gigya.android.sdk.network.adapter.VolleyNetworkProvider$2.onResponse(VolleyNetworkProvider.java:184)
W/System.err:     at com.gigya.android.sdk.network.adapter.VolleyNetworkProvider$2.onResponse(VolleyNetworkProvider.java:179)
W/System.err:     at com.gigya.android.sdk.network.adapter.VolleyNetworkProvider$VolleyNetworkRequest.deliverResponse(VolleyNetworkProvider.java:281)
W/System.err:     at com.gigya.android.sdk.network.adapter.VolleyNetworkProvider$VolleyNetworkRequest.deliverResponse(VolleyNetworkProvider.java:219)
W/System.err:     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:907)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:216)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
`

**Comment by tal-mi** [comment]
Thank you for notifying us.
We will investigate this issue and update accordingly.

**Comment by tal-mi** [comment]
Hi,

I suggest you go ahead and open a support case in order for us to properly address this issue.
https://developers.gigya.com/display/GD/Opening+A+Support+Incident
I believe it will benefit if we can do a live session.

**Comment by tal-mi** [comment]
Please verify on the latest 5.1.1 release.
Thanks.

**Comment by tal-mi** [comment]
Hi,
Do you have an update regarding this issue?
Tested on our end on version 5.1.2 with no isses.

**Comment by IuliaSTANA** [comment]
No, still have the same issue with version 5.1.2. Same exception.

**Comment by tal-mi** [comment]
Closing (obsolete)
