### ISSUE TITLE
Where I can download Core library prior to 4.2?

### ISSUE THREAD

**Issue by volodia-chornenkyi-discovery** [SAP/gigya-android-sdk#25]
As Core library 4.2+ integrates native Google Sign In, I want to use version 4.0 or 4.1 to be eligible for making API calls during migration from deprecated v3.x.
But artifacts are available only starting from v4.2. Where I can download the Core library aar prior to 4.2?

**Comment by volodia-chornenkyi-discovery** [comment]
Okay, I was able to find the v4.0.6 version in this commit: a41e7dbe75aed10009536d0077a5ebf58fd33200

@tal-mi could you confirm that this version would still work after the deprecation of v3.x on September 13,2021 mentioned here: https://help.sap.com/viewer/8b8d6fffe113457094a17701f63e3d6a/GIGYA/en-US/4145b78970b21014bbc5a10ce4041860.html ?

This does not mean that we won't update to v4.2 or v5.x later but there is no clear understanding of when the issue with Google Sign In will be resolved.

**Comment by tal-mi** [comment]
Prior versions 4.+ will work but will have several security issues that were fixed.
There is no issue with Giigke Sign in. I believe it is an implementation issue that we will be able to resolve togeter.
