### ISSUE TITLE
GigyaWebBridge socialize.addConnection failing for apple

### ISSUE THREAD

**Issue by iNdieboyjeff** [SAP/gigya-android-sdk#27]
Using gigya SDK 5.1.3
Via the web bridge when calling socialize.addConnection we get an error:
<img width="682" alt="Screenshot 2021-08-12 at 11 28 13" src="https://user-images.githubusercontent.com/851270/129173594-1c30a2f5-ec1e-480f-9e80-4b4163d40283.png">

Downgrading to SDK 5.0.1 we get directed to the Apple ID login screen as expected

I've checked the generated URLs and there are differences in the query string generated to socialize.addConnection

**5.1.3:**

- client_id
- oauth_token
- redirect_uri
- response_type
- sig
- timestamp=1628758546&
- x_provider
- x_sdk
- x_secret_type

**5.0.1:**

- client_id
- nonce
- oauth_token
- redirect_ur
- response_type
- sig
- timestamp
- ucid
- x_provider
- x_sdk
- x_secret_type

**Comment by iNdieboyjeff** [comment]
Have checked and this was also working in 5.1.2, so looks like a regression in 5.1.3

**Comment by tal-mi** [comment]
I will investigate and update.

Thank you.

**Comment by tal-mi** [comment]
Seems the request is missing a mandatory authentication parameter.
If this is a regression issue I will fix it and release a patched version as soon as I can.
Will continue to update this thread.

Thanks again.

Tal

**Comment by tal-mi** [comment]
Issue identified.

Will be resolved in the upcoming update.
Expected 22-23 of August.

Regards,
Tal

**Comment by tal-mi** [comment]
Version 5.1.4 is available.

**Comment by tal-mi** [comment]
Hi,
Do you still experience issues with the latest build?

**Comment by iNdieboyjeff** [comment]
I’ve not had a chance to check as I’m in the middle of a release. I’ll see if I can give it a try this week.

**Comment by iNdieboyjeff** [comment]
Apologies for the delayed response.  However everything seems to be working with the latest version :)

**Comment by tal-mi** [comment]
Thank you for the update.
