### ISSUE TITLE
Android Facebook Login - WebView no longer supported

### ISSUE THREAD

**Issue by iNdieboyjeff** [SAP/gigya-android-sdk#28]
Facebook is no longer allowing login using WebView.  If we use WebLoginActivity `com.gigya.android.sdk.ui.WebLoginActivity` then login with Facebook does not work.  What can we do instead?  Does this need to be resolved SDK side, or do we need to alter our implementation?

**Comment by tal-mi** [comment]
Facebook login requires implementing the Facebook SDK.
If you do the SDK will not use the WebLoginActity.
Please see:
https://sap.github.io/gigya-android-sdk/sdk-core/#facebook

**Comment by iNdieboyjeff** [comment]
FacebookProvider.isAvailable returns `true`

At the moment I'm failing to see anything that looks wrong from the documentation
