### ISSUE TITLE
Close Window CTA does not close window

### ISSUE THREAD

**Issue by VanyaHuamanBottleRocket** [SAP/gigya-android-sdk#29]
Scenario: Sign in with google, conflicting accounts found, linkToSocial(apple), Go through login flow for apple, arrive on empty screen with CTA of "Close Window", tap on "Close Window". I have noticed that at the end of a login flow using apple a CTA will show saying "Close Window" but when I click on it nothing happens. I have also encountered this in the sample app when I use "Login with Provider" and use apple. I don't get the flow but I do see a "Close Window" CTA that doesn't seem to do anything.

**Comment by tal-mi** [comment]
Close window is not supported in the web interface bridge. It is a cause of an error in your setup.
