### ISSUE TITLE
Embed proguard rules

### ISSUE THREAD

**Issue by cristan** [SAP/gigya-android-sdk#3]
Obfuscated builds [fail](https://stackoverflow.com/q/46660558/389649) with Gigya. A solution is off course to not do any obfuscating / optimizing for the entire library, but this is very imprecise and keeps way more than needed. It also is still an (undocumented) action users of your library would need to do.

A much better solution would be if your libraries would include these ProGuard rules, just like every major library does these days. You can specify it like this:

```
android {
    defaultConfig {
        consumerProguardFiles 'lib-proguard-rules.pro'
    }
```

This way, all projects which will use your this library will automatically get the ProGuard rules you defined. You can determine exactly what needs to be objuscated which in turn would result in smaller apps for your customers.

Another solution would be to add @Keep annotations to the classes which need to be kept, so you won't need ProGuard rules at all.

**Comment by tal-mi** [comment]
Embedded proguard rules are currently out of scope.
I will update if changes apply.
