### ISSUE TITLE
HttpNetworkProvider signs first request in queue twice

### ISSUE THREAD

**Issue by AARazbakov** [SAP/gigya-android-sdk#30]
In class `HttpNetworkProvider` in method `release()` first request is signed first time

`
_requestFactory.sign(queued.getRequest());
`

and the will be signed again in 

`queued.run();
`

Is that expected behavior? Other requests will be signed only once in `run()`.

**Comment by tal-mi** [comment]
Probably not. I will check that and update.
Signing the request twice is irrelevant and should not cause issues but if not needed I will alter the behavior.

Thanks,
Tal

**Comment by AARazbakov** [comment]
> Signing the request twice is irrelevant and should not cause issues but if not needed I will alter the behavior.

Yes, I don't see here any negative side effect, thanks.

**Comment by tal-mi** [comment]
The networking layer rewrite is comping up next Q. 
Closing this issue.
