### ISSUE TITLE
GigyaWebBridge doesn't contain fix to clear all cookies in correct way

### ISSUE THREAD

**Issue by AARazbakov** [SAP/gigya-android-sdk#31]
In class `GigyaWebBridge` in method `clearCookies()` called on logout.
There is no fix https://github.com/SAP/gigya-android-sdk/commit/1918358b38863a7afa512057ec8f057d35d9f80d applied for `Presenter`

**Comment by tal-mi** [comment]
Fix will be available in an upcoming version.
In addition a boolean setter will be added to the main Gigya interface to enable/disable cookie clearing.

**Comment by tal-mi** [comment]
Updated in v5.1.6.
