### ISSUE TITLE
RuntimeException: Error creating Gigya SDK (did you forget to Gigya.setApplication or missing apiKey?)

### ISSUE THREAD

**Issue by lo-g** [SAP/gigya-android-sdk#32]
Hi! I'm facing this crash while doing explicit init within release config:

```
init {
        GigyaLogger.setDebugMode(BuildConfig.DEBUG)
        Gigya.setApplication(application)
        Gigya.secureActivityWindow(BuildConfig.DEBUG.not())
    }

    private val instance = Gigya.getInstance(GigyaAccount::class.java).apply {
        init(
            "MY-API-KEY",
            "MY_DOMAIN"
        )
    }
```

```
  isMinifyEnabled = true
  isShrinkResources = true
  isDebuggable = false
```

Any ideas? 
With debug config all woks well.

Gigya core version: **core-v5.1.4**

**Comment by tal-mi** [comment]
Hi,

Are you using the JSON configuration "gigyaSdkConfiguration.json" file?

Tal

**Comment by lo-g** [comment]
Hi, nope because my goal is to initialize it dynamically. When my app starts I fetch API key and domain from a server and then I'm trying to initialize Gigya.

**Comment by tal-mi** [comment]
Initiate the Gigya.getInstance(GigyaAccount::class.java) call only after you receive the API key.
Once the instance is created the SDK fetches required configurations from the server. The API Key is mandatory at that point.

**Comment by tal-mi** [comment]
An initialization fix was applied in v5.1.5.
Please update and verify.

**Comment by lo-g** [comment]
Thanks for support, with v5.1.5 the crash is still present. I've created a simple project [here](https://github.com/lo-g/gigya-test) where you can reproduce the issue.

**Comment by tal-mi** [comment]
Thank you. I will verify and update.

**Comment by tal-mi** [comment]
Hi.
The SDK currently does not support minification. 
You will need to add it to your proguard rules.
-keep class com.gigya.android.sdk.** { *; }

**Comment by lo-g** [comment]
Thanks @tal-mi. I've added this rules.

**Comment by burhanshakir** [comment]
@tal-mi  Unfortunately, I am facing the same issue as above even after adding the `-keep class com.gigya.android.sdk.** { *; } `rule to the proguard file. I am on the v7.0.3 of the Android SDK and this is how I am initialising the SDK in the application class:

```
GigyaLogger.setDebugMode(BuildConfig.DEBUG)
Gigya.setApplication(this)
Gigya.getInstance().init(BuildConfig.SAP_API_KEY, "eu1.gigya.com")
```

I am also using the Gigya NSS SDK, not sure if that could be causing an issue here ?
