### ISSUE TITLE
Google sign-in is not working in Amazon FireTab

### ISSUE THREAD

**Issue by mukeshdiscovery** [SAP/gigya-android-sdk#39]
When I upgraded from Gigya 4.0.6 to v5.2.0, google sign-in in not working in Firetab. Its is working in android devices and android tablet but not working in amazon Firetab. I have all the required dependency as mention in integration guide mentioned here 

https://sap.github.io/gigya-android-sdk/sdk-core/

 Gigya SDK :  com.github.SAP.gigya-android-sdk:sdk-core:core-v5.2.0'
 Google auth: com.google.android.gms:play-services-auth:19.2.0

I am getting the below exception:

 java.lang.RuntimeException: Google auth library implementation is a required dependency. Please make sure it is correctly implemented in your build.gradle file.
    https://sap.github.io/gigya-android-sdk/sdk-core/#google
        at com.gigya.android.sdk.providers.ProviderFactory.getProviderClass(ProviderFactory.java:94)
        at com.gigya.android.sdk.providers.ProviderFactory.providerFor(ProviderFactory.java:47)
        at com.gigya.android.sdk.api.BusinessApiService.login(BusinessApiService.java:235)

I am guessing since there in no Google play services and Google Play Store in Amazon FireTab, so it is failing. Pls confirm.

Please let me know how we can enable the google sign-in in Amazon FireTab.

**Comment by tal-mi** [comment]
Hi,

Correct. Google Play Services is a prerequisite for implementing Google Sign in on an Android device.
https://developers.google.com/identity/sign-in/android/start-integrating

I agree that the exception message is misleading. It will be changed accordingly.

**Comment by mukeshdiscovery** [comment]
Thank you @tal-mi

**Comment by tal-mi** [comment]
Exception message updated and will be available in the next release.
