### ISSUE TITLE
Account available after logout

### ISSUE THREAD

**Issue by rberghegger** [SAP/gigya-android-sdk#4]
dependency: gigya-android-sdk-core:core-v4.2.1

After successfully executing `gigya.logout()` a call to `gigya.getAccount()` would still return the last account, although `gigya.isLoggedIn()` returns false.

I would expect the SDK to not deliver the last account after successful logout.

**Comment by tal-mi** [comment]
Thank you for your insight.
I will evaluate this issue and update.

**Comment by tal-mi** [comment]
Invalidation of cached account is missing in main logout logic.
Will be added to next scheduled release.

**Comment by tal-mi** [comment]
Issue resolved on latest version 4.2.3.

Cheers,
Tal
