### ISSUE TITLE
Add support for apps targeting Android S and above

### ISSUE THREAD

**Issue by andresesfm** [SAP/gigya-android-sdk#43]
Android applications are now required to target Android S and higher.

In order to do that, applications have to keep these behavior changes into consideration: https://developer.android.com/about/versions/12/behavior-changes-12

Of particular concern for this library is the security change related to the immutability of PendingIntents described here: https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

Not including a flag explicitly marking a request as mutable/immutable will cause an exception if the client app targets Android S or higher.

The following PR: https://github.com/SAP/gigya-android-sdk/pull/42 fixes this issue by conditionally adding the immutable flag depending on the Android version, hence maintaining backward compatibility.

**Comment by tal-mi** [comment]
Updated via versions:
tfa-v2.1.0
auth-v2.2.0
Thanks for your contribution.
