### ISSUE TITLE
GoogleProviderWrapper constructor is inaccessible

### ISSUE THREAD

**Issue by josefgrunig** [SAP/gigya-android-sdk#45]
Google login with the new external providers fails because the private Constructor:

java.lang.IllegalAccessException: Class java.lang.Class<com.gigya.android.sdk.containers.IoCContainer> cannot access  method void com.mypackage.myapp.gigya.providers.GoogleProviderWrapper.<init>(android.content.Context) of class java.lang.Class<com.mypackage.myapp.gigya.providers.GoogleProviderWrapper>

GoogleProviderWrapper constructor has to be declared public

**Comment by tal-mi** [comment]
Hi, 
looking into it.
Planned update on Sunday. I will push it though.
Tal

**Comment by tal-mi** [comment]
Fixed the issue. 
Will be deployed in the upcoming version (upcoming days).

**Comment by tal-mi** [comment]
Fixed in v7.0.1.
