### ISSUE TITLE
check specific API response onHide() callback

### ISSUE THREAD

**Issue by MandaliaBhavik** [SAP/gigya-android-sdk#47]
I am showing the Login/Registration Screen-set on click of the button using  below code.  I am passing the pre-defined Screen-set name/ID.
```
gigya.showScreenSet(screenSet,
            true, map,
            object : GigyaPluginCallback<MyAccount>()
```
Above code is opening registration form by GigyaSDK using webview . On clilck of the Submit button I am getting the below callback.

```
override fun onHide(event: GigyaPluginEvent, reason: String?) {
                    Log.d(GIGYA, "onHide" + reason)
                    if (reason != null) {
                        when (reason) {
                           gigya.verifySession()
                            GigyaDefinitions.Plugin.FINISHED -> 	{                                                            
                                    if (gigya.isLoggedIn) {
                                        gigya.getAccount(true,object : GigyaCallbackMyAccount>() {
                                            override fun onSuccess(obj: MyAccount?) {                                    
                                                    callBack.onSuccess(account)
                                                }
                                            }
                                            override fun onError(error: GigyaError?) {
                                                callBack.onError(error?.localizedMessage!!)
                                               
                                            }
                                        })
                             	}
                                
                                return
                            }
                            GigyaDefinitions.Plugin.CANCELED -> {
                                callBack.onError(reason)
                                Log.d(GIGYA, "OnCancelled")
                            }

                        }
                    }
                }
```

Problem :: On click of Submit button, Admin team is hitting one API which is `accounts.finalizeregistration()` to set the user data into their database. But i am getting the onHide() callback very instantly as soon as the form is finished. But API call is still running in the background and due to this whenever i tried to fetch the updated userAccount data, i am getting error from SDK.

- So Is there any way to check the API call is completed successfully and there after i can proceed with the UI updation at my end ?
- Also I am getting the callback early before completion of the final API call so is there anything that need to be done from Admin side or mobile side ?

**Comment by tal-mi** [comment]
On Admin side, make sure "isFlowFinalized" is not being sent with the onHide event before the async flow is completed.
The flow is managed in the WebSDK it needs to delay the onHide event until it is completed.
If this information is insufficient you will need to open a [support case](https://github.com/SAP/gigya-android-sdk#how-to-obtain-support) so WEB SDK team can handle this as the mobile is agnostic to admin flows.
