### ISSUE TITLE
Can't retrieve core-v6.1.1 from jitpack

### ISSUE THREAD

**Issue by DiegoSaa** [SAP/gigya-android-sdk#49]
Hello,

implementation 'com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v6.1.1'

When I'm trying to build, I get the following error:

`> Could not resolve all files for configuration ':app:garageDevDebugRuntimeClasspath'.
   > Could not resolve com.github.SAP.gigya-android-sdk:sdk-core:core-v6.1.1.
     Required by:
         project :app > project :gigya-sdk
      > Could not resolve com.github.SAP.gigya-android-sdk:sdk-core:core-v6.1.1.
         > Could not get resource 'https://s3.amazonaws.com/salesforcesos.com/android/maven/release/com/github/SAP/gigya-android-sdk/sdk-core/core-v6.2.1/sdk-core-core-v6.2.1.pom'.
            > Could not GET 'https://s3.amazonaws.com/salesforcesos.com/android/maven/release/com/github/SAP/gigya-android-sdk/sdk-core/core-v6.2.1/sdk-core-core-v6.2.1.pom'. Received status code 403 from server: Forbidden`

**Comment by tal-mi** [comment]
Hi,
Experiencing a Github issue due to a recent update. Looking into it.
As a workaround, you can implement the aar locally.
https://github.com/SAP/gigya-android-sdk/releases/tag/core-v6.1.1

**Comment by tal-mi** [comment]
Issue resolved.
https://jitpack.io/com/github/SAP/gigya-android-sdk/core-v6.1.1/build.log
Please verify.
