### ISSUE TITLE
UnknownHostException is not treated as a network error

### ISSUE THREAD

**Issue by rberghegger** [SAP/gigya-android-sdk#5]
dependency: gigya-android-sdk-core:core-v4.2.1

After enabling the airplane mode on my Android device a call to `gigya.login()` (for example) results in a `GigyaError` with code 0 and the message "java.net.UnknownHostException:[...]".
Unfortunately this code does not match the code for "Network error" (see https://developers.gigya.com/display/GD/Response+Codes+and+Errors).

**Comment by tal-mi** [comment]
This message occurs only when using Volley as your network provider library.
Nevertheless, you are correct that the error structure should be aligned to standards.
I will address this issue and update when update will be available.

Thanks.

**Comment by tal-mi** [comment]
Error will be aligned to the following:
400106 | Not connected | User is not connected to the required network or to any network.
Will be available in next update.

**Comment by tal-mi** [comment]
Issue resolved on latest version 4.2.3.

Cheers,
Tal
