### ISSUE TITLE
Social Login: Invalid redirect uri

### ISSUE THREAD

**Issue by skyphantomhz** [SAP/gigya-android-sdk#50]
Hi,
I'm working on social login (Microsoft, apple and Twitter). But got screen `Failed connecting` when i inspect the web view both of them return message.
```{
errorCode: 400011,
errorMessage: 'Invalid redirect uri',
requestId: '84303c1f1cfc4a91b3fed7fa6317468d',
callId: '84303c1f1cfc4a91b3fed7fa6317468d'}
```

The docs([gigya-mircrosoft](https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/41656e5d70b21014bbc5a10ce4041860.html) [gigya-twitter](https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/417ceb5b70b21014bbc5a10ce4041860.html)) recommend me add url like `https://socialize.au1.gigya.com/GS/GSLogin.aspx` but i see the sdk use 
```final String redirectUri = "gigya://gsapi/" + context.getPackageName() + "/login_result";```
Then i replace redirectUri to url (https://socialize.au1.gigya.com/GS/GSLogin.aspx) and paste to browser, the error not happen.

Please help me

**Comment by skyphantomhz** [comment]
Hi, Anything new regarding this issue?

**Comment by tal-mi** [comment]
redirect Uri should include your application id / package (context.getPackageName())
In addition, see that you have whitelisted the redirect URI in your console.
