### ISSUE TITLE
Documentation inconsistency for Android and iOS

### ISSUE THREAD

**Issue by laxmi-sap** [SAP/gigya-android-sdk#53]
Hi Team,

There is a documentation issue highlighted by one of the customers.

The description highlighted in Italics below is added under different sections on both Android and iOS links.
If you follow the screenshots then you will see that this description is under **Interruptions** section [1] for **Android** whereas the same is under **Business API** section [2] for **iOS**.

Description (as in documentation):
'_The plugin callback is also typed to the current Account schema.'
'Business APIs are provided in order to give you an easier interface. If a more detailed and customized use is required, you can still use the
If a more detailed and customized use is required, you can still use the generic Gigya.send interface for all request purposes.'_

[1]https://sap.github.io/gigya-android-sdk/sdk-core/#interruptions
[2]https://sap.github.io/gigya-swift-sdk/GigyaSwift/#business-apis

Can we get it corrected?
Thanks
Laxmi.

![iOS Business APIs Description](https://github.com/SAP/gigya-android-sdk/assets/138779796/35ffa55f-ae28-47b8-bcab-f80a6f43721b)
![Android Business APIs Description](https://github.com/SAP/gigya-android-sdk/assets/138779796/b3b562a3-fcca-46c9-8cc2-f5f7b8e36f31)

**Comment by tal-mi** [comment]
Fixed.
