### ISSUE TITLE
Social wrappers - R8/proguard

### ISSUE THREAD

**Issue by mare011** [SAP/gigya-android-sdk#56]
New approach for providing Wrapper classes in gigya.providers requires it to be excluded with R8/proguard.
Can you add it to embedded config in AAR if you plan to support it: https://github.com/SAP/gigya-android-sdk/issues/3
Or to update the documentation and mention that rules needs to be added manually for:

```
-keep class com.gigya.android** { *; }
-keep class gigya.providers** { *; }
```
And to keep classes that gson will use, like custom class that extends **GigyaAccount**

**Comment by tal-mi** [comment]
I will add it to the docs until embedded config support is applied.
Thanks.
