### ISSUE TITLE
[Gigya-Nss] Plugins crash with "Methods marked with @UiThread must be executed on the main thread.

### ISSUE THREAD

**Issue by huytrinh68** [SAP/gigya-android-sdk#57]
Hi @tal-mi and all
I'm trying to install SDK for React Native project (with Java code, not Kotlin). After I install gigya-nss and gigya-nss engine. I got this issue with gigya-nss engine. Can you help me to check this? Thank
<img width="622" alt="Screenshot 2023-08-23 at 18 26 02" src="https://github.com/SAP/gigya-android-sdk/assets/47779052/21532aa2-d0c7-4629-9016-64ef94595ba1">
<img width="675" alt="Screenshot 2023-08-24 at 01 06 51" src="https://github.com/SAP/gigya-android-sdk/assets/47779052/e17d04a7-ff87-420f-88a7-12170c6b5141">

**Comment by tal-mi** [comment]
Gigya NSS is not officially supporting react-native plugin.
It is designed only for native implementations of the SDKS.
Supporting plugins (react/flutter) is currently not in the pipeline.
Only via FR using the [SAP standard support](https://help.sap.com/viewer/8b8d6fffe113457094a17701f63e3d6a/GIGYA/en-US/4167e8a470b21014bbc5a10ce4041860.html) request.

**Comment by huytrinh68** [comment]
Thank you for your reply @tal-mi
