### ISSUE TITLE
[CRASH][7.0.5] Systematic crash when there is no internet connection

### ISSUE THREAD

**Issue by FraVaccAcc** [SAP/gigya-android-sdk#60]
Hi,
Implementing the 7.0.5 version i have a crash whenever i try to make a request to gigya without internet connection my apps keep crashing due to gigya, without any log. Downgrading to version 7.0.4 i have no issues in this case.

Prerequisites:

- Version 7.0.5
- No internet connection

How:

- Do any request to gigya
- Systematic crash without any log in logcat

**Comment by tal-mi** [comment]
Do you have a crash log / stack trace so I can send it for investigation?

**Comment by FraVaccAcc** [comment]
> Do you have a crash log / stack trace so I can send it for investigation?

No, i don't because as i said there is no clear evidence in the stacktrace. But you can easily reproduce it disabling internet on your devices with gigya 7.0.5

**Comment by tal-mi** [comment]
Hi,

I identified the issue on the new OkHttpAdapter. I have instructed the team to prioritize and fix it.
As a temporary workaround, you can remove the OKHTTP implementations in your application and it will fall back to using the native HttpAdapter and the issue will not occur.

Thanks,
Tal

**Comment by tal-mi** [comment]
Fixed in version 7.0.6
