### ISSUE TITLE
social login not work

### ISSUE THREAD

**Issue by Greathfs** [SAP/gigya-android-sdk#61]
I use the example, I configure apikey and apiDomain, and then I type in messenger, and then I click the social login button, and the page looks like this
![image](https://github.com/SAP/gigya-android-sdk/assets/18097997/af626c21-e98b-4366-947d-62ab49a3fbe5)

**Comment by Greathfs** [comment]
<img width="1337" alt="image" src="https://github.com/SAP/gigya-android-sdk/assets/18097997/be6565b3-619c-4314-a1b7-971165cc3ef7">

**Comment by Greathfs** [comment]
<img width="1267" alt="image" src="https://github.com/SAP/gigya-android-sdk/assets/18097997/57c7f18c-cdb6-4f74-9f95-49371d7d40db">

**Comment by Greathfs** [comment]
<img width="1264" alt="image" src="https://github.com/SAP/gigya-android-sdk/assets/18097997/92d2a60e-5811-4a21-8e74-cbdeb17dbbff">

**Comment by Greathfs** [comment]
https://socialize.eu1.gigya.com/socialize.login?client_id=4_TweK0gdZ47NqO1pQRldNMA&gmid=gmid.ver4.AcbHi9iHpA.9d2IUeIOsXZCyvXN4ZEoP4YW81KmK-NTXYneYUNqjDST6OBjICkagUmTxRnfYlWF.UnbPAu1ZNjeRaSScTnLaljKNgxxLQthY7VKkyerA1bedG9DT-kYRKa2netYZt7LQVph55XtCl9vWBCTnqDBcgg.sc3&nonce=1698218161438_-404005309&redirect_uri=gigya%3A%2F%2Fgsapi%2Fcom.gigya.android.sample%2Flogin_result&response_type=token&ucid=giWi-NXkDIKf84y9Sd-9EQ&x_provider=messenger&x_sdk=7.0.6&x_secret_type=oauth1

**Comment by Greathfs** [comment]
finally,it will show this page
<img width="881" alt="image" src="https://github.com/SAP/gigya-android-sdk/assets/18097997/62f11e3f-10be-4597-b0c5-fa29b790d3c0">

**Comment by Greathfs** [comment]
@tal-mi hi,can u help to slow down this problem?

**Comment by tal-mi** [comment]
Hi,
I am assuming you followed the correct setup on your console regarding microsoft social provider?
https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/41656e5d70b21014bbc5a10ce4041860.html?q=identity%20providers

I don't see your cname implementation in the configuration json file.

**Comment by Greathfs** [comment]
I think there is no problem with the configuration item, because our iOS development colleagues have already adjusted it, but the Android side can not log in successfully. I asked my iOS developer colleague and used the same method as mine, but he was able to log in. Can you provide a sample code that can successfully log in to Microsoft? I'll revise our project with reference. Thank you. @tal-mi

**Comment by Greathfs** [comment]
If I configure cname, the resulting web link will look like this:
http://cdc.hisense-europe.com/socialize.login?client_id=4_TweK0gdZ47NqO1pQRldNMA&gmid=gmid.ver4.AcbHi9iHpA.9d2IUeIOsXZCy vXN4ZEoP4YW81KmK-NTXYneYUNqjDST6OBjICkagUmTxRnfYlWF.UnbPAu1ZNjeRaSScTnLaljKNgxxLQthY7VKkyerA1bedG9DT-kYRKa2netYZt7LQVph5 5XtCl9vWBCTnqDBcgg.sc3&nonce=1700046178948_-532373351&redirect_uri=gigya%3A%2F%2Fgsapi%2Fcom.gigya.android.sample%2Flogi N_result & the payload = token&ucid = bXw6K3zxjKHwCVHAR6w3ng & x_provider = messenger&x _sdk = 7.0.6 & x_secret_type = oauth1

It doesn't feel right, I think it should start with this: socialize.eu1.gigya.com.

**Comment by tal-mi** [comment]
Hi,
your redirect url is "gigya://gsapi/com.gigya.android.sample/login_result" (attached above). In your site settings (console) you have typed an incorrect trusted site URL "gigya://gsapi.com.hisense.juconnect.connectlife/login_result"
Please correct to "gigya://gsapi/com.hisense.juconnect.connectlife/login_result" and try again (I do not have the permissions to do it on your site).

**Comment by Greathfs** [comment]
I use our app, the redirect url is "gigya://gsapi/com.hisense.juconnect.connectlife/login_result", the full link is "https://socialize.eu1.gigya.com/socialize.login?client_id=4_TweK0gdZ47NqO1pQRldNMA&gmid=gmid.ver4.AcbHOHaaYg.Uhm1X-eScL-ZxnowkBVMPpa_pLY9hFcl11QzpXDr0Th1Fwd5Yos8gmvrTr8_QSiR.j--XDVdLTI1BJV19HvwgpoKZULolEWKul_vP_qXbZDCnTrFERHuXbEwB328jNDk6i9swH47_Hkpda7bgNYfI4w.sc3&nonce=1698133530000_988417284&redirect_uri=gigya%3A%2F%2Fgsapi%2Fcom.hisense.juconnect.connectlife%2Flogin_result&response_type=token&ucid=v6DZ_ilcqBdhGuFb7m_ZrA&x_provider=apple&x_sdk=7.0.6&x_secret_type=oauth1"

it also can not login success

**Comment by Greathfs** [comment]
I downloaded the SDK source code from this website, and then I found our iOS development colleagues, found that the logic of Android SDK and iOS SDK logic is not the same, I changed the Android SDK code, you can pull up the Microsoft login page, but after Microsoft login success, It still prompts me that a link has failed to load. If necessary, I can send you the example I have written for debugging.
Here are the changes I made to the Android SDK
![WX20231212-180344@2x](https://github.com/SAP/gigya-android-sdk/assets/18097997/9ee82008-45c3-4b46-a9d4-f6a84c6e678f)

**Comment by Greathfs** [comment]
Does it matter if I change this url? But if I don't change it, I can't pull up the Microsoft login page, and after changing it, I can get up the Microsoft login page, but it still can't succeed after Microsoft login

**Comment by Greathfs** [comment]
The following is the screenshot of the configuration provided by our cloud development colleagues. Is there any problem?
![image](https://github.com/SAP/gigya-android-sdk/assets/18097997/db07215e-dbfd-45d6-bf47-149f5ca734bd)

**Comment by Greathfs** [comment]
@tal-mi Please look at this question, thank you

**Comment by Greathfs** [comment]
Here is the logic of the iOS SDK
<img width="934" alt="image" src="https://github.com/SAP/gigya-android-sdk/assets/18097997/b7c96035-3a8a-4545-983c-194ba3fc1e0d">

**Comment by Greathfs** [comment]
The Microsoft login page is displayed after successful login

网页无法打开
位于 gsapi://login_result#errorDetails=Missing+required+fields+for+registration%3a+preferences.terms.connectlife_terms_conditions.isConsentGranted%2c+preferences.privacy.connectlife_privacy_policy.isConsentGranted&id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJFUTBNVVE1TjBOQ1JUSkVNemszTTBVMVJrTkRRMFUwUTBNMVJFRkJSamhETWpkRU5VRkJRZyIsImRjIjoiZXUxIn0.eyJpc3MiOiJodHRwczovL2ZpZG0uZ2lneWEuY29tL2p3dC80X1R3ZUswZ2RaNDdOcU8xcFFSbGROTUEvIiwic3ViIjoiYThjMTMxOWVjNWRmNDZiMmE0MjM1NWVhZmQ2MDM0NjciLCJpYXQiOjE3MDIzNzgxMTUsImV4cCI6MTcwMjM3ODE3NSwiaXNMb2dnZWRJbiI6ZmFsc2V9.eaHs6IddqyV8N0-2i5lvO2XSmJqOeH6tCyvLXXz79VReAhvS4an5ygMf2nmcDRucGFJ_oR55uPPfhwa7Dipf2_YV913yb5MEMbs4tfK35l2MEljCJ6Rdni1_JEDW5RSEuPQsgf9YqOTSmQ_29h50X4ZpttDZBYQA6GS9wErokgRJaI5zFl0NFMnzpqObnbSwFBP6Scy8W_M2sy-vMqY46s4Fdwco92p31HKqR-u-prfjx3jZhhfs4-acad3mO3fv-5MrX7CRguzno9s4ltndCwe6WIL5c-cKkh5rc9qBGTkaf_DrzknzbD2QBFYDec-2kr5DT3GnMIVGMwC_j_YNUQ&x_regToken=st2.s.AcbHVWkkMA.e2njbYQ2M9BSDIlEj1NRMRHc7yVVzI9Q4GqkzfxRfo-CrNbnvV-umpJe6ff9SwyhenvIib-QPYHszeQVe4uoKhGNHedryh-m0W8p-AYTVastBPuGYFezmYlFqckm2xdh.euOo7HZJLq21hnr9UPFGFiTEM4nQD9DbDUumbyPuM1oI65dpnz-MAsJuEUYO_x3qZojHgy9aleZQSU7uKuYJ-Q.sc3&error=pending_registration&error_description=206001+-+Account+Pending+Registration 的网页无法加载，因为：

net::ERR_UNKNOWN_URL_SCHEME
