### ISSUE TITLE
Missing releases 7.0.5 and 7.0.6 release

### ISSUE THREAD

**Issue by inovakotnik** [SAP/gigya-android-sdk#62]
Missing 7.0.5 and 7.0.6 releases

https://mvnrepository.com/artifact/com.github.SAP.gigya-android-sdk/sdk-core?repo=scijava-public

**Comment by tal-mi** [comment]
Hi,

7.0.5 has a network bug. Better use 7.0.6.
We have transitions to SAP MavenCentral group (finally).
Please use:
https://central.sonatype.com/artifact/com.sap.oss.gigya-android-sdk/sdk-core
