### ISSUE TITLE
Could not find com.github.SAP.gigya-android-sdk:sdk-core:core-v7.0.6

### ISSUE THREAD

**Issue by bgolob** [SAP/gigya-android-sdk#67]
Hello,

there was a crash issue with sdk-core v.7.0.5 when SDK was initiated without the internet connection. The issue is solved in the 7.0.6 version but that version is not yet available on the Maven repository. Please publish the latest version.

**Comment by tal-mi** [comment]
Version 7.0.6 is available.
https://sap.github.io/gigya-android-sdk/sdk-core/#configuration
Now transitioning to maven central under SAP oss.

**Comment by bgolob** [comment]
It's not visible yet here: https://mvnrepository.com/artifact/com.github.SAP.gigya-android-sdk/sdk-core and I'm still getting: Could not find com.github.SAP.gigya-android-sdk:sdk-core:core-v7.0.6.
