### ISSUE TITLE
Could not resolve com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v5.1.2

### ISSUE THREAD

**Issue by delphinebugner** [SAP/gigya-android-sdk#69]
### Checklist

- [ ] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-android-sdk#sap-cdc-gigya-android-sdk) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-android-sdk/blob/main/CODE_OF_CONDUCT.md).

### Description

I receive the following error when building on GitHub actions: 

Similar to https://github.com/SAP/gigya-android-sdk/issues/51 and https://github.com/SAP/gigya-android-sdk/issues/49
```
FAILURE: Build failed with an exception.

* What went wrong:

Could not determine the dependencies of task ':app:buildProductionReleasePreBundle'.
> Could not resolve all task dependencies for configuration ':app:productionReleaseRuntimeClasspath'.
   > Could not resolve com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v5.1.2.
     Required by:
         project :app > project :gigya-react-native
      > Could not resolve com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v5.1.2.
         > Could not get resource 'https://repo-player.fr/maven/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.1.2/gigya-android-sdk-core-core-v5.1.2.pom'.
            > Could not GET 'https://repo-player.fr/maven/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.1.2/gigya-android-sdk-core-core-v5.1.2.pom'. Received status code 403 from server: Forbidden
```

We are still using jitpack as we do not plan to upgrade the Gigya SDK from 5.1.2 to 7.0.X - is this correct we can not use maven without upgrading?

### Reproduction

I followed the step described in https://sap.github.io/gigya-android-sdk/sdk-core/#implement-using-jitpack-will-be-soon-deprecated---moving-to-maven-central

1. Root build.gradle : 
```
allprojects {
    repositories {
        google()
        mavenCentral()
        // @gigya 
         maven { url 'https://jitpack.io' }
        // @player
        maven {
            url "https://repo-player.fr/maven/"
        }
    }
}
```
2. App build.gradle: 
```
dependencies {
  implementation 'com.github.SAP.gigya-android-sdk:gigya-android-sdk-core:core-v5.1.2'
  implementation 'com.google.code.gson:gson:2.8.5' // required dependency of the Gigya SDK
}
``` 

### Additional context

I do not have the error building locally on my Mac, only on CD (using a Linux virtual machine).

### SDK version

5.1.2

**Comment by delphinebugner** [comment]
Update : the deployment succeeded today, without further action in my team ; I'm closing it now.

I checked on the CD and the `curl https://jitpack.io/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.1.2/build.log` did return `Build ok` before the build succeeded

**Comment by delphinebugner** [comment]
Hello, I'm reopeining this as my deployments are re-failing because of this error!

Even when having `curl https://jitpack.io/com/github/SAP/gigya-android-sdk/gigya-android-sdk-core/core-v5.1.2/build.log` returning "build ok" locally

Does anyone have insights on this?

**Comment by tal-mi** [comment]
https://jitpack.io/com/github/SAP/gigya-android-sdk/core-v5.1.2/build.log
Build is back up.

Jitpack has a tendency to drop builds. that's why we moved to MavenCentral from version 7+.

**Comment by delphinebugner** [comment]
We haven't made the upgrade to 7+ because we don't want to disconnect all our users - I've seen it in the doc and seen it by testing; @tal-mi do you also confirm it?

Do you plan to fully drop Jitpack at some point? Or do you plan to add 5+ version on maven (could be wonderful🙏!!)

**Comment by EliottG-Bam** [comment]
Hello, I have the same problem and my deployments are re-failing because of this error
Is it possible to make the build available once again please? @tal-mi 

As asked earlier, do you plan on dropping Jitpack / adding 5+ versions on maven?

**Comment by tal-mi** [comment]
HIi,

I have made 5.1.2 available again on Jitpack
https://jitpack.io/com/github/SAP/gigya-android-sdk/core-v5.1.2/build.log

We are currently not planning to add 5+ to maven.
v5 use old cryptography key which are flagged as insecure by Google. 
This will not be approved.

**Comment by delphinebugner** [comment]
Thanks for the answer @tal-mi , that's clear 🙂

**Comment by gnivsarkar007** [comment]
Hello! Experiencing the same problem on CD, for the same version!
