### ISSUE TITLE
Google sign in via play-services-auth is deprecated

### ISSUE THREAD

**Issue by Philio** [SAP/gigya-android-sdk#71]
### Checklist

- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-android-sdk#sap-cdc-gigya-android-sdk) and have not found a suitable solution.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-nSS/blob/main/CODE_OF_CONDUCT.md#code-of-conduct).

### Describe the problem you'd like to have solved.

GoogleProviderWrapper and documentation are still using `play-services-auth` library for Google sign in, which is deprecated in favour of Credential Manager and will be removed next year

### Describe the ideal solution.

GoogleProviderWrapper to be updated to use Credential Manager

### Alternatives or workarounds

N/A

### Additional context

N/A

**Comment by levistepanov** [comment]
and... the MR is where?

**Comment by Philio** [comment]
It was a feature request?

**Comment by tal-mi** [comment]
In the works.

**Comment by marcor-a** [comment]
Any updates here?

**Comment by tal-mi** [comment]
Transitioning from GMS to Credentials manager is currently in development. Expected soon.
Support for idToken is request in our server side and is currently under review.
