### ISSUE TITLE
Execution failed for task ':app:checkDevDebugAarMetadata'.

### ISSUE THREAD

**Issue by emreakcan** [SAP/gigya-android-sdk#75]
### Checklist

- [X] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-android-sdk#sap-cdc-gigya-android-sdk) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-android-sdk/blob/main/CODE_OF_CONDUCT.md).

### Description

Builds fail due 
Execution failed for task ':app:checkDevDebugAarMetadata'.

``FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:checkDevDebugAarMetadata'.

> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.

   > Could not find com.github.SAP.gigya-android-sdk:sdk-core:core-v7.1.0.

     Searched in the following locations:

       - https://dl.google.com/dl/android/maven2/com/github/SAP/gigya-android-sdk/sdk-core/core-v7.1.0/sdk-core-core-v7.1.0.pom

       - https://repo.maven.apache.org/maven2/com/github/SAP/gigya-android-sdk/sdk-core/core-v7.1.0/sdk-core-core-v7.1.0.pom

       - https://jitpack.io/com/github/SAP/gigya-android-sdk/sdk-core/core-v7.1.0/sdk-core-core-v7.1.0.pom

       - https://plugins.gradle.org/m2/com/github/SAP/gigya-android-sdk/sdk-core/core-v7.1.0/sdk-core-core-v7.1.0.pom

       - file:/home/****/workspace/LIV_Golf_MR-1612/android/app/libs/sdk-core-core-v7.1.0.jar

       - file:/home/****/workspace/LIV_Golf_MR-1612/android/app/libs/sdk-core.jar

       - https://storage.googleapis.com/download.flutter.io/com/github/SAP/gigya-android-sdk/sdk-core/core-v7.1.0/sdk-core-core-v7.1.0.pom

       - https://jcenter.bintray.com/com/github/SAP/gigya-android-sdk/sdk-core/core-v7.1.0/sdk-core-core-v7.1.0.pom

     Required by:

         project :app

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

> Get more help at https://help.gradle.org/.

BUILD FAILED in 4m 4s

Running Gradle task 'assembleDevDebug'...                         245.5s

Gradle task assembleDevDebug failed with exit code 1

script returned exit code 1`
`

### Reproduction

Trying to create an apk, but pom file is not found

https://jitpack.io/com/github/SAP/gigya-android-sdk/sdk-core/core-v7.1.0/sdk-core-core-v7.1.0.pom

Git error. Max repo size 500MB exceeded

### SDK version

7.1.0 or 7.0.1

**Comment by emreakcan** [comment]
what I noticed is
https://jitpack.io/com/github/SAP/gigya-android-sdk/sdk-core/core-v7.0.1/sdk-core-core-v7.0.1.pom
returning "Not found" every now and then, I think that is causing the issue

**Comment by tal-mi** [comment]
Do not use Jitpack for v7 builds.
Move to maven central builds only.
https://sap.github.io/gigya-android-sdk/sdk-core/#implement-using-mavencentral
