### ISSUE TITLE
Issue with user registration with params on sdk 7.1.3 version

### ISSUE THREAD

**Issue by ve00ym803** [SAP/gigya-android-sdk#78]
### Checklist

- [X] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-android-sdk#sap-cdc-gigya-android-sdk) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-android-sdk/blob/main/CODE_OF_CONDUCT.md).

### Description

I am using this dependency (i.e. com.sap.oss.gigya-android-sdk:sdk-core:7.1.3) to register a new user to gigya account using android sdk. 

If I am setting params as empty it gets registered successfully but when I try to send some extra data in params, it shows error as: 

{
  "callId": "49627e62fd614b70b2d72c99ee0b5ee3",
  "errorCode": 400006,
  "errorDetails": "Invalid argument: Invalid JSON in 'profile'",
  "errorMessage": "Invalid parameter value",
  "apiVersion": 2,
  "statusCode": 400,
  "statusReason": "Bad Request",
  "time": "2024-11-12T14:50:28.577Z"
}

### Reproduction

Code to reproduce error: 

                val phoneMap: MutableMap<String, Any> = HashMap()
                phoneMap["type"] = "mobile"
                phoneMap[NUMBER_KEY] = phone.value!!
                phoneMap["default"] = true

                val profileMap: MutableMap<String, Any> = HashMap()
                profileMap[FIRST_NAME_KEY] = fullName.value!!
                profileMap[COUNTRY_KEY] = BuildConfig.COUNTRY_VALUE
                profileMap[PHONE_KEY] = arrayListOf(phoneMap)

                val requestParams: MutableMap<String, Any> = HashMap()
                requestParams[PROFILE_KEY] = profileMap

                Log.w(TAG, "signUp: $requestParams")

                gigya.register(
                    emailSignUp.value,
                    passwordSignUp.value,
                    requestParams,
                    object : GigyaLoginCallback<GigyaResponse>() {
                        override fun onSuccess(response: GigyaResponse?) {

                        }

                        override fun onError(error: GigyaError?) {
                            
                        }
                    }
                )
            }
        }

### SDK version

7.1.3

**Comment by tal-mi** [comment]
Hi,

Mapped parameters (values) need to be JSON serialized before sending them. 

***The profile object is a JSON object holding the user's profile fields and is stored in the user's Account object.***
See: 
https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/41698a3870b21014bbc5a10ce4041860.html?q=accounts.register
