### ISSUE TITLE
Crash on social login

### ISSUE THREAD

**Issue by bruzzers** [SAP/gigya-android-sdk#9]
we have a Problem on our app, we are using Gigya for social login with Facebook, Google, Amazon and Apple login and we find this crash:

**SdkGigyaRepository$socialLoginAndRegistration$2$invokeSuspend$$inlined$suspendCoroutine$lambda$1.onError(SdkGigyaRepository.java:10)
com.gigya.android.sdk.api.BusinessApiService$9.onApiSuccess (BusinessApiService.java:39)
com.gigya.android.sdk.api.ApiService$1.onResponse (ApiService.java:73)
com.gigya.android.sdk.network.adapter.HttpNetworkProvider$GigyaNetworkAsyncTask.onPostExecute (HttpNetworkProvider.java:58)
com.gigya.android.sdk.network.adapter.HttpNetworkProvider$GigyaNetworkAsyncTask.onPostExecute (HttpNetworkProvider.java:2)
android.os.AsyncTask.finish (AsyncTask.java:755)
android.os.AsyncTask.access$900 (AsyncTask.java:192)
android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:772)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7948)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)**

as you can see we are using coroutines, is it a problem?

Do you have some advice for use to avoid this crash?

Thank you

**Comment by tal-mi** [comment]
Hi, 

Will be happy to help.
Can you please provide the entire crash log? This seems like just part of the data as it does not indicate the crash reason.
A summary of your usage flow or code snippets will be helpful as well.

Thanks,
Tal

**Comment by bruzzers** [comment]
i'm sorry i Forget this:

**Fatal Exception: java.lang.IllegalStateException
Already resumed
kotlin.coroutines.SafeContinuation.resumeWith (SafeContinuation.java:2)**

`override fun onError(error: GigyaError) { // Fail
                                continuation.resume(handleGigyaError(error))
                            }`

this is the code for the onError method

**Comment by tal-mi** [comment]
Seems like your corutine is being resumed more than once.
This may indicate that there are multiple callback calls in the same task which is a problem.
Try to debug and check this issue.
What API are you calling? does this happen in a specific flow?
If you provide more data it will help me investigate the issue quicker.

Thanks

**Comment by bruzzers** [comment]
Hi,
the error happens when the app call a social login using the Gigya SDK (no REST API)


```
getGigyaInstance()
    .login(provider, params, object : GigyaLoginCallback<GigyaAccount>() {
    ......
}
```

**Comment by tal-mi** [comment]
Any specific provider?

**Comment by bruzzers** [comment]
we don't know the specific provider cause the Log doesn't told us which provider is, but in app we have only social login with:
**Facebook, Amazon, Google and Apple Login**

**Comment by tal-mi** [comment]
Add this line anywhere is your code. Preferably in an application extension class.
GigyaLogger.setDebugMode(true);
You would be able to view additional logs the SDK triggers for more information.
I will try to investigate if there are multiple callback calls happening in a single flow.

**Comment by tal-mi** [comment]
Is there any additional information available?

**Comment by bruzzers** [comment]
Hi,
we have already set the debug mode on true, but this is an app on play store, so we can't use it.

We are finding many many crash on this already resume.

The Problem is that we can't reproduce this crash on our phone or emulator.

**Comment by tal-mi** [comment]
I suggest you go ahead and open a support case in order for us to properly investigate the issue.
https://developers.gigya.com/display/GD/Opening+A+Support+Incident

**Comment by tal-mi** [comment]
Hi,

Is there any progress on your end concerning this issue?
